# ============================================================
# preprocessing.py — Dataset Preparation for Bus Overcrowding Detection
# ============================================================
"""
Responsibilities
─────────────────
1. Walk a raw image folder (data/raw/) and collect images + labels.
2. Resize / normalise images.
3. Split into train / val / test sets.
4. Generate YOLOv8-compatible dataset.yaml.
5. Optionally augment training images (flips, brightness, noise, etc.)
   to expand small custom datasets.

Run standalone:
    python preprocessing.py --raw-dir data/raw --out-dir data/dataset
"""

import argparse
import random
import shutil
import textwrap
from pathlib import Path
from typing import List, Tuple, Optional

import cv2
import numpy as np

import config
from logger import logger

# ─────────────────────────────────────────────
# CONSTANTS
# ─────────────────────────────────────────────
SUPPORTED_IMG_EXT = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}
YOLO_CLASS_NAMES  = ["person"]           # Only class we care about


# ─────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────

def collect_image_label_pairs(raw_dir: Path) -> List[Tuple[Path, Optional[Path]]]:
    """
    Walk raw_dir recursively and pair each image with its corresponding
    YOLO .txt label file (same stem, .txt extension).  Label may be None
    if annotations have not been created yet (images-only workflow).
    """
    pairs = []
    for img_path in sorted(raw_dir.rglob("*")):
        if img_path.suffix.lower() not in SUPPORTED_IMG_EXT:
            continue
        label_path = img_path.with_suffix(".txt")
        pairs.append((img_path, label_path if label_path.exists() else None))

    logger.info(f"Found {len(pairs)} images in {raw_dir} "
                f"({sum(1 for _, l in pairs if l)} with labels)")
    return pairs


def resize_image(img: np.ndarray, size: Tuple[int, int] = (640, 640)) -> np.ndarray:
    """Resize with letterboxing to preserve aspect ratio."""
    h, w     = img.shape[:2]
    target_w, target_h = size
    scale    = min(target_w / w, target_h / h)
    new_w    = int(w * scale)
    new_h    = int(h * scale)
    resized  = cv2.resize(img, (new_w, new_h), interpolation=cv2.INTER_LINEAR)

    # Pad to exact target size
    canvas   = np.full((target_h, target_w, 3), 114, dtype=np.uint8)
    pad_top  = (target_h - new_h) // 2
    pad_left = (target_w - new_w) // 2
    canvas[pad_top:pad_top + new_h, pad_left:pad_left + new_w] = resized
    return canvas


def split_pairs(
    pairs: List[Tuple[Path, Optional[Path]]],
    train: float = config.TRAIN_SPLIT,
    val: float   = config.VAL_SPLIT,
    seed: int    = config.RANDOM_SEED,
) -> Tuple[List, List, List]:
    """Randomly shuffle and split pairs into train / val / test."""
    rng = random.Random(seed)
    shuffled = list(pairs)
    rng.shuffle(shuffled)

    n       = len(shuffled)
    n_train = int(n * train)
    n_val   = int(n * val)

    train_set = shuffled[:n_train]
    val_set   = shuffled[n_train:n_train + n_val]
    test_set  = shuffled[n_train + n_val:]

    logger.info(f"Split: train={len(train_set)} val={len(val_set)} test={len(test_set)}")
    return train_set, val_set, test_set


def write_split(
    pairs: List[Tuple[Path, Optional[Path]]],
    split_dir: Path,
    resize: bool = True,
) -> None:
    """Copy images (and labels) into the appropriate split subdirectory."""
    img_dir = split_dir / "images"
    lbl_dir = split_dir / "labels"
    img_dir.mkdir(parents=True, exist_ok=True)
    lbl_dir.mkdir(parents=True, exist_ok=True)

    for img_path, lbl_path in pairs:
        # Read and optionally resize
        img = cv2.imread(str(img_path))
        if img is None:
            logger.warning(f"Cannot read image, skipping: {img_path}")
            continue
        if resize:
            img = resize_image(img, config.PREPROCESS_RESIZE)

        dest_img = img_dir / img_path.name
        cv2.imwrite(str(dest_img), img)

        # Copy label (create empty label if missing — unlabelled negative sample)
        dest_lbl = lbl_dir / (img_path.stem + ".txt")
        if lbl_path:
            shutil.copy(str(lbl_path), str(dest_lbl))
        else:
            dest_lbl.touch()

    logger.info(f"Wrote {len(pairs)} samples to {split_dir}")


def write_dataset_yaml(dataset_dir: Path) -> Path:
    """Generate the dataset.yaml required by Ultralytics YOLO training."""
    yaml_content = textwrap.dedent(f"""\
        # Auto-generated by preprocessing.py
        path: {dataset_dir.resolve()}
        train: train/images
        val:   val/images
        test:  test/images

        nc: {len(YOLO_CLASS_NAMES)}
        names: {YOLO_CLASS_NAMES}
    """)
    yaml_path = dataset_dir / "dataset.yaml"
    yaml_path.write_text(yaml_content)
    logger.info(f"dataset.yaml written to {yaml_path}")
    return yaml_path


# ─────────────────────────────────────────────
# AUGMENTATION
# ─────────────────────────────────────────────

class Augmentor:
    """
    Lightweight offline augmentation for the training split.
    Each augmentation is applied to a copy of the image;
    YOLO .txt labels (bounding boxes) are transformed accordingly.
    """

    def __init__(self, seed: int = config.RANDOM_SEED):
        self.rng = random.Random(seed)
        self.np_rng = np.random.default_rng(seed)

    # ── Individual transforms ─────────────────────────────────────────

    def horizontal_flip(
        self, img: np.ndarray, boxes: np.ndarray
    ) -> Tuple[np.ndarray, np.ndarray]:
        """Flip image left-right and mirror box x-centres."""
        flipped = cv2.flip(img, 1)
        if boxes.size:
            boxes = boxes.copy()
            boxes[:, 1] = 1.0 - boxes[:, 1]   # x_center = 1 - x_center
        return flipped, boxes

    def brightness_contrast(
        self, img: np.ndarray, boxes: np.ndarray
    ) -> Tuple[np.ndarray, np.ndarray]:
        """Random brightness (±40) and contrast (0.7–1.3) jitter."""
        alpha = self.np_rng.uniform(0.7, 1.3)
        beta  = int(self.np_rng.integers(-40, 40))
        adjusted = cv2.convertScaleAbs(img, alpha=alpha, beta=beta)
        return adjusted, boxes

    def gaussian_noise(
        self, img: np.ndarray, boxes: np.ndarray
    ) -> Tuple[np.ndarray, np.ndarray]:
        """Add Gaussian noise to simulate low-light or compressed video."""
        noise = self.np_rng.normal(0, 15, img.shape).astype(np.int16)
        noisy = np.clip(img.astype(np.int16) + noise, 0, 255).astype(np.uint8)
        return noisy, boxes

    def motion_blur(
        self, img: np.ndarray, boxes: np.ndarray, ksize: int = 7
    ) -> Tuple[np.ndarray, np.ndarray]:
        """Simulate camera shake / bus motion."""
        kernel = np.zeros((ksize, ksize))
        kernel[ksize // 2, :] = 1.0 / ksize
        blurred = cv2.filter2D(img, -1, kernel)
        return blurred, boxes

    def random_crop(
        self, img: np.ndarray, boxes: np.ndarray, min_scale: float = 0.8
    ) -> Tuple[np.ndarray, np.ndarray]:
        """Random crop then resize back — simulates zoom variation."""
        h, w = img.shape[:2]
        scale = self.np_rng.uniform(min_scale, 1.0)
        new_h = int(h * scale)
        new_w = int(w * scale)
        top   = int(self.np_rng.integers(0, h - new_h + 1))
        left  = int(self.np_rng.integers(0, w - new_w + 1))
        crop  = img[top:top + new_h, left:left + new_w]
        crop  = cv2.resize(crop, (w, h), interpolation=cv2.INTER_LINEAR)

        # Adjust boxes (YOLO normalised format)
        if boxes.size:
            boxes = boxes.copy()
            # Convert to pixel absolute, clip, rescale
            cx    = boxes[:, 1] * w
            cy    = boxes[:, 2] * h
            bw    = boxes[:, 3] * w
            bh    = boxes[:, 4] * h
            x1    = cx - bw / 2
            y1    = cy - bh / 2
            x2    = cx + bw / 2
            y2    = cy + bh / 2

            # Shift by crop offset and rescale
            x1 = (x1 - left) * (w / new_w)
            y1 = (y1 - top)  * (h / new_h)
            x2 = (x2 - left) * (w / new_w)
            y2 = (y2 - top)  * (h / new_h)

            # Clip to [0, image_size]
            x1 = np.clip(x1, 0, w)
            y1 = np.clip(y1, 0, h)
            x2 = np.clip(x2, 0, w)
            y2 = np.clip(y2, 0, h)

            # Drop boxes that lost most of their area
            area_orig = (boxes[:, 3] * w) * (boxes[:, 4] * h)
            area_new  = (x2 - x1) * (y2 - y1)
            keep      = (area_new / (area_orig + 1e-6)) > 0.3

            cx_new = ((x1 + x2) / 2) / w
            cy_new = ((y1 + y2) / 2) / h
            bw_new = (x2 - x1) / w
            bh_new = (y2 - y1) / h

            boxes = np.column_stack([
                boxes[:, 0], cx_new, cy_new, bw_new, bh_new
            ])[keep]

        return crop, boxes

    # ── Apply augmentation pipeline ───────────────────────────────────

    def augment(
        self,
        img: np.ndarray,
        boxes: np.ndarray,
        n: int = config.AUGMENTATION_FACTOR,
    ) -> List[Tuple[np.ndarray, np.ndarray]]:
        """
        Produce `n` augmented versions of (img, boxes).
        Each version applies a random subset of transforms.
        """
        transforms = [
            self.horizontal_flip,
            self.brightness_contrast,
            self.gaussian_noise,
            self.motion_blur,
            self.random_crop,
        ]
        results = []
        for _ in range(n):
            aug_img  = img.copy()
            aug_boxes = boxes.copy() if boxes.size else boxes
            # Apply 2–4 random transforms
            chosen = self.rng.sample(transforms, k=self.rng.randint(2, 4))
            for t in chosen:
                aug_img, aug_boxes = t(aug_img, aug_boxes)
            results.append((aug_img, aug_boxes))
        return results


def augment_train_split(train_dir: Path) -> None:
    """
    Apply offline augmentation to all images in the training split.
    Augmented images are written back into the same train/images folder.
    """
    augmentor = Augmentor()
    img_dir   = train_dir / "images"
    lbl_dir   = train_dir / "labels"

    originals = list(img_dir.glob("*"))
    logger.info(f"Augmenting {len(originals)} training images "
                f"(factor={config.AUGMENTATION_FACTOR})…")

    for img_path in originals:
        if img_path.suffix.lower() not in SUPPORTED_IMG_EXT:
            continue
        img = cv2.imread(str(img_path))
        if img is None:
            continue

        lbl_path = lbl_dir / (img_path.stem + ".txt")
        boxes    = _read_yolo_labels(lbl_path)

        augmented = augmentor.augment(img, boxes, n=config.AUGMENTATION_FACTOR)

        for idx, (aug_img, aug_boxes) in enumerate(augmented, start=1):
            stem    = f"{img_path.stem}_aug{idx}"
            out_img = img_dir / f"{stem}{img_path.suffix}"
            out_lbl = lbl_dir / f"{stem}.txt"

            cv2.imwrite(str(out_img), aug_img)
            _write_yolo_labels(out_lbl, aug_boxes)

    logger.info("Augmentation complete.")


def _read_yolo_labels(path: Path) -> np.ndarray:
    """Parse a YOLO .txt label file into an (N, 5) float array."""
    if not path.exists() or path.stat().st_size == 0:
        return np.empty((0, 5))
    rows = []
    for line in path.read_text().strip().splitlines():
        parts = list(map(float, line.split()))
        if len(parts) == 5:
            rows.append(parts)
    return np.array(rows) if rows else np.empty((0, 5))


def _write_yolo_labels(path: Path, boxes: np.ndarray) -> None:
    """Write (N, 5) float array back to YOLO .txt format."""
    lines = []
    for row in boxes:
        cls, cx, cy, bw, bh = row
        lines.append(f"{int(cls)} {cx:.6f} {cy:.6f} {bw:.6f} {bh:.6f}")
    path.write_text("\n".join(lines))


# ─────────────────────────────────────────────
# MAIN PIPELINE
# ─────────────────────────────────────────────

def run_preprocessing(
    raw_dir: Path       = config.RAW_DIR,
    out_dir: Path       = config.DATASET_DIR,
    augment: bool       = True,
) -> Path:
    """
    Full preprocessing pipeline:
      collect → split → resize + copy → augment → generate yaml
    Returns path to dataset.yaml.
    """
    logger.info("=== Preprocessing Pipeline Start ===")

    pairs              = collect_image_label_pairs(raw_dir)
    if not pairs:
        logger.error(f"No images found in {raw_dir}. "
                     "Place your raw images (+ optional .txt labels) there.")
        raise FileNotFoundError(f"No images in {raw_dir}")

    train_set, val_set, test_set = split_pairs(pairs)

    write_split(train_set, out_dir / "train")
    write_split(val_set,   out_dir / "val")
    write_split(test_set,  out_dir / "test")

    if augment and train_set:
        augment_train_split(out_dir / "train")

    yaml_path = write_dataset_yaml(out_dir)

    logger.info("=== Preprocessing Pipeline Complete ===")
    return yaml_path


# ─────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Bus Overcrowding — Dataset Preprocessing")
    parser.add_argument("--raw-dir",  type=Path, default=config.RAW_DIR)
    parser.add_argument("--out-dir",  type=Path, default=config.DATASET_DIR)
    parser.add_argument("--no-augment", action="store_true")
    args = parser.parse_args()

    run_preprocessing(
        raw_dir=args.raw_dir,
        out_dir=args.out_dir,
        augment=not args.no_augment,
    )
